---
- name: Wait for LES RPC port to go up
  wait_for:
    host: 'localhost'
    port: '{{ geth_rpc_port }}'
    delay: 5
    state: drained

- name: Get enode address
  uri:
    url: http://localhost:{{ geth_rpc_port }}/
    method: POST
    body: '{"id": 1, "method": "admin_nodeInfo"}'
    body_format: json
    return_content: yes
  register: node_info

- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ geth_name }}'
    consul_services:
      - name: '{{ geth_name }}'
        tags: ['les', 'geth']
        # we advertise the port with basic auth
        port: '{{ geth_port }}'
        meta:
          env: '{{ env }}'
          stage: '{{ stage }}'
          node_addr: '{{ node_info.json.result.id }}'
          node_enode: '{{ node_info.json.result.enode }}'
        checks:
          - id: '{{ geth_name }}-status'
            name: LES Geth Health
            type: tcp
            tcp: 'localhost:{{ geth_port }}'
