---
- name: Create directories for geth
  file:
    path: '{{ geth_keys }}'
    state: directory
    owner: dockremap
    recurse: true

- name: Find all enode files
  find:
    paths: '{{ geth_keys }}'
    patterns: 'UTC--*'
    file_type: file
  register: account_files

- name: Set Geth password to be empty
  copy:
    dest: '{{ geth_keys }}/password'
    content: ''

- name: Generate Geth account
  docker_container:
    name: '{{ geth_name }}'
    image: '{{ geth_image }}'
    pull: true
    auto_remove: yes
    command: |
      account new
      --keystore=/keys
      --password=/keys/password
    volumes:
      - '{{ geth_vol }}/keys:/keys:rw'
  when: account_files.files | length == 0
