---
# general container config
cont_state: started
cont_recreate: false
cont_restart: false

# OAuth2 provided by Google
oauth2_proxy_port: 8090
oauth2_proxy_image: 'statusteam/oauth2-proxy:2.2.0'

# Root password
bootstrap__root_pass: '{{lookup("passwordstore", "hosts/admin-pass")}}'

# Consul Encryption
consul_encryption_key: '{{lookup("passwordstore", "services/consul/encryption-key")}}'
