---
# Run les-goerli.misc fleet on Ropsten
geth_network_name: goerli
geth_cont_name: les-geth-full
geth_sync_mode: full
geth_data_path: /data
geth_cont_image: 'ethereum/client-go:v1.8.27'
geth_log_level_name: info

# geth metrics
geth_source_cont_name: '{{ geth_cont_name }}'
geth_expo_cont_name: '{{ geth_cont_name }}-metrics'
