---
# Run les-main.misc fleet on Mainnet
geth_network_name: mainnet
geth_cont_name: les-geth-full
geth_sync_mode: full
geth_data_path: /data
geth_cont_image: 'ethereum/client-go:v1.8.17'
geth_log_level_name: info
