---
geth_image: 'ethereum/client-go:v1.8.17'
geth_name: 'les-geth-full'

# container beaviour
cont_state: started
cont_restart: false
cont_recreate: false

geth_vol: '/docker/{{ geth_name }}'
geth_keys: '{{ geth_vol }}/keys'
# RPC port of administration
geth_rpc_port: 8545
# 1=Frontier, 2=Morden (disused), 3=Ropsten, 4=Rinkeby
geth_network: 3
# Maximum percentage of time allowed for serving LES requests (0-90)
geth_light_serv: 90
# Maximum number of LES client peers (default: 100)
geth_light_peers: 200
# Port to listen on
geth_port: 30303
# Memory to use
geth_cache: 1536

# resources limits to avoid killing the host
cont_mem_ratio: 0.7
cont_mem_limit: '{{ (ansible_memtotal_mb * cont_mem_ratio|float) | int }}'
cont_swap_limit: '{{ (cont_mem_limit|int) + (ansible_swaptotal_mb * cont_mem_ratio|float) | int }}'
